### ISSUE TITLE
Where to add native dependencies?

### ISSUE THREAD

**Issue by hrueger** [NativeScript/plugin-seed#1]
Hi,
first of all this is super useful and easy to work with.

I just have a question: Where can I add my native dependencies (for android)? 

If I add it to `tools/assets/App_Resources/Android/app.gradle`, it will be used for *all* plugins in this workspace, or not?
I'd like to add it to just one plugin.

**Comment by NathanWalker** [comment]
@hrueger Hi - great question (forgive the bot for auto closing this - we need to turn that off 😆 ) - You will do that as usual in the package for the particular plugin. For example you can reference our own internal suite of plugins here:
https://github.com/NativeScript/plugins/tree/master/packages/fingerprint-auth/platforms/android

That package has a `platforms` folder as usual containing the native code needed for the package.

**Comment by hrueger** [comment]
Yes, that works. Thank you!
