### ISSUE TITLE
Remove package

### ISSUE THREAD

**Issue by wuilmerj24** [NativeScript/plugin-seed#21]
Is it possible to remove the package from the cli?

**Comment by NathanWalker** [comment]
Hi @wuilmerj24 do you mean after adding a package to the workspace, and then remove from the workspace?
If so, you can use `npm run remove-package` - it will prompt for name of package to remove and will then cleanup all the files associated with it.

**Comment by wuilmerj24** [comment]
@NathanWalker  Yes. Thanks
