### ISSUE TITLE
How to use an Angular component + template

### ISSUE THREAD

**Issue by hrueger** [NativeScript/plugin-seed#5]
I'm trying to create an Angular-only plugin. I want to add an Angular component and a template. So I put the component file and the template file in `packages/nativescript-squirrel-chat-ui/angular` and added it to the `declarations` of the module in `index.ts`. But now I have two problems:
When building the plugin, it says `
```
ERROR: Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("bble-content">
                        <GridLayout rows="auto, auto">
                            [ERROR ->]<Label class="sendername" row="0" *ngIf="!isContinuing(item) && !item.fromMe" [text]="item.sender.nam")
The pipe 'date' could not be found ("

                        <FlexboxLayout class="meta">
                            <Label [text]="[ERROR ->]item.date | date:'shortTime'" class="time"></Label>
                            <Label [text]="getSt")
```

So I removed the date pipe and changed `*ngIf` to `[visibility]="[...] ? 'visible' : 'hidden'"`. Now the plugin builds successfully.

However, when I try to use the component in the `demo-angular` app, it is just blank.

My plugin is here: https://github.com/SchoolSquirrel/nativescript-plugins/tree/main/packages/nativescript-squirrel-chat-ui

Do you have any idea?

**Comment by NathanWalker** [comment]
@hrueger make sure the plugin's module includes `NativeScriptCommonModule` as that's where ngIf comes from etc.:
https://github.com/SchoolSquirrel/nativescript-plugins/blob/main/packages/nativescript-squirrel-chat-ui/angular/index.ts#L8

You can always debug step through code in chrome dev tools to see how your plugin is behaving in the demo app.

**Comment by hrueger** [comment]
@NathanWalker Oh thanks, I missed the `NativeScriptCommonModule`. Sorry for that. Now it builds without any errors, however, the demo app still shows blank space where the UI is supposed to be.

Chrome Dev Tools show this:
![grafik](https://user-images.githubusercontent.com/18656830/94050307-5dfe5880-fdd6-11ea-974d-c8cdbc100b97.png)

The `tests` label shows, but below it there is just nothing...

**Comment by hrueger** [comment]
@NathanWalker Sorry for another ping, but it's been almost two weeks ;-)

**Comment by NathanWalker** [comment]
@hrueger sorry for late reply here - from looks of your repo seems you got past this?

**Comment by hrueger** [comment]
@NathanWalker No, unfortulately, not. The `demo-angular` app still only displays the `tests` label (see comment above)

**Comment by cvietor** [comment]
@hrueger 
2 minor issues there with your code:

- Rename your `SquirrelChatUiModule` in `packages/nativescript-squirrel-chat-ui/angular` to NativeScriptSquirrelChatUiModule for example, because otherwise you have a naming conflict with the SquirrelChatUiModule in your demo-angular project.
- Export your `NativescriptSquirrelChatUiComponent` from that module

```
import { CUSTOM_ELEMENTS_SCHEMA, NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativescriptSquirrelChatUiComponent } from './nativescript-squirrel-chat-ui.component';
import { NativeScriptCommonModule } from "@nativescript/angular";

@NgModule({
    declarations: [
        NativescriptSquirrelChatUiComponent,
    ],
    imports: [
        NativeScriptCommonModule,
    ],
    schemas: [
        NO_ERRORS_SCHEMA,
        CUSTOM_ELEMENTS_SCHEMA,
    ],
    exports: [
      NativescriptSquirrelChatUiComponent
    ]
})
export class NativescriptSquirrelChatUiModule {}
```

Import your `NativescriptSquirrelChatUiModule` in the demo-angular's `squirrel-chat-ui.module.ts`
```
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptCommonModule, NativeScriptRouterModule } from '@nativescript/angular';
import { SquirrelChatUiComponent } from './squirrel-chat-ui.component';
import { NativescriptSquirrelChatUiModule } from '@schoolsquirrel/nativescript-squirrel-chat-ui/angular';

@NgModule({
	imports: [
            NativeScriptCommonModule, 
            NativescriptSquirrelChatUiModule, 
            NativeScriptRouterModule.forChild([{ path: '', component: SquirrelChatUiComponent }])],
	declarations: [SquirrelChatUiComponent],
	schemas: [NO_ERRORS_SCHEMA],
})
export class SquirrelChatUiModule {}

```

Then you should be good to go...

**Comment by hrueger** [comment]
@cvietor Thanks a lot!
